package com.cpy.settings.mapper;

import com.cpy.settings.domain.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     * 根据id删除用户
     * @mbggenerated Wed May 18 17:16:22 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     * 插入用户
     * @mbggenerated Wed May 18 17:16:22 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed May 18 17:16:22 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     * 根据id查询用户
     * @mbggenerated Wed May 18 17:16:22 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     * 根据id修改用户  选择性修改  可以修改也可以修改部分
     * @mbggenerated Wed May 18 17:16:22 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Wed May 18 17:16:22 CST 2022
     */
    int updateByPrimaryKey(User record);
}